// The browser→desktop account handoff ("link device") — the pure payload
// half. Shared by the web page that confirms the handoff and the desktop app
// that receives it, so both sides agree on the exact shape and on what is
// refused. No crypto here on purpose: the caller encrypts the serialized
// payload with NIP-44 to the one-time key before it ever reaches a URL.
//
// Protocol, end to end:
//
//   1. The desktop generates a one-time secp256k1 keypair and a random nonce,
//      and opens the system browser at
//        https://<web>/link-device?pub=<64-hex one-time pubkey>&nonce=<nonce>&cb=creaton://identity
//   2. The web page shows who would be shared and asks for confirmation.
//   3. On confirm the page builds the payload below and NIP-44-encrypts it
//      with the ACCOUNT key as the sender and `pub` as the recipient, then
//      redirects to
//        <cb>?p=<base64url of the NIP-44 payload>&from=<64-hex account pubkey>
//      `from` is mandatory: a NIP-44 payload does not identify its sender,
//      so the desktop cannot derive the conversation key without it.
//   4. The desktop decrypts with its one-time secret key and `from` as the
//      sender key and MUST:
//        - reject a payload whose `nonce` is not the one it generated,
//        - reject a payload whose `exp` is in the past (5-minute lifetime),
//        - reject a payload whose `sk` does not derive `from` (the sender
//          must be handing over its own account — sender binding),
//        - mark the nonce spent after one successful use (single-use).
//
// The web side refuses any callback that is not a `creaton://` URL — a
// redirect to an attacker-controlled http(s) URL would turn this page into an
// open redirect that hands the account key to whoever crafted the link.
//
// Payload JSON — exactly these four fields, in this order, nothing else:
//
//   {"v":1,"sk":"<64-hex account secret key>","nonce":"<the nonce>","exp":<unix seconds>}

/** Payload schema version. Bump on any shape change. */
export const LINK_DEVICE_PAYLOAD_VERSION = 1;

/** How long a freshly built payload stays acceptable: 5 minutes. */
export const LINK_DEVICE_TTL_MS = 5 * 60 * 1000;

/** The one URL scheme a handoff may return to. */
export const LINK_DEVICE_CB_SCHEME = "creaton:";

/** Nonce alphabet and length bounds the desktop must generate within. */
const NONCE_RE = /^[A-Za-z0-9_-]{8,128}$/;

const PUBKEY_RE = /^[0-9a-fA-F]{64}$/;

/**
 * The account handoff payload. Serialized with `serializeLinkDevicePayload`
 * to the exact JSON shape documented at the top of this module.
 */
export type LinkDevicePayload = {
  /** Schema version — `LINK_DEVICE_PAYLOAD_VERSION`. */
  v: number;
  /** Account secret key, 64-char lowercase hex. */
  sk: string;
  /** The one-time nonce generated by the desktop; binds the payload. */
  nonce: string;
  /** Expiry, unix seconds. The desktop rejects anything past this. */
  exp: number;
};

/** Result of parsing or checking: the value, or the reason it was refused. */
export type LinkDeviceResult<T> =
  | { ok: true; value: T }
  | {
      ok: false;
      error:
        | "malformed"
        | "nonce-mismatch"
        | "expired"
        | "missing-param"
        | "bad-pubkey"
        | "bad-nonce"
        | "bad-callback";
    };

/** The three URL parameters the desktop's link carries. */
export type LinkDeviceRequest = {
  /** One-time public key the payload is encrypted to, 64-hex. */
  pub: string;
  /** One-time nonce the payload must carry back, verbatim. */
  nonce: string;
  /** Where to hand the ciphertext back — must be a `creaton://` URL. */
  cb: string;
};

const BASE64URL_ALPHABET =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

/** UTF-8 to base64url (no padding). Pure — no platform globals. */
export function encodeBase64Url(text: string): string {
  const bytes = new TextEncoder().encode(text);
  let out = "";
  for (let i = 0; i < bytes.length; i += 3) {
    const b0 = bytes[i];
    const b1 = i + 1 < bytes.length ? bytes[i + 1] : undefined;
    const b2 = i + 2 < bytes.length ? bytes[i + 2] : undefined;
    out += BASE64URL_ALPHABET[b0 >> 2];
    out += BASE64URL_ALPHABET[((b0 & 3) << 4) | ((b1 ?? 0) >> 4)];
    if (b1 === undefined) break;
    out += BASE64URL_ALPHABET[((b1 & 15) << 2) | ((b2 ?? 0) >> 6)];
    if (b2 === undefined) break;
    out += BASE64URL_ALPHABET[b2 & 63];
  }
  return out;
}

/** base64url (no padding) to UTF-8. Throws on malformed input. */
export function decodeBase64Url(encoded: string): string {
  if (encoded.length % 4 === 1 || /[^A-Za-z0-9_-]/.test(encoded)) {
    throw new Error("not base64url");
  }
  const bytes: number[] = [];
  for (let i = 0; i < encoded.length; i += 4) {
    const chunk = encoded.slice(i, i + 4);
    const values = [...chunk].map((c) => BASE64URL_ALPHABET.indexOf(c));
    while (values.length < 4) values.push(0);
    bytes.push((values[0] << 2) | (values[1] >> 4));
    if (chunk.length > 2)
      bytes.push(((values[1] & 15) << 4) | (values[2] >> 2));
    if (chunk.length > 3) bytes.push(((values[2] & 3) << 6) | values[3]);
  }
  return new TextDecoder().decode(new Uint8Array(bytes));
}

/**
 * True when `cb` is a callback the handoff may redirect to: a parseable
 * `creaton://` URL with nothing smuggled in around it. Everything else —
 * http(s), javascript:, data:, relative paths — is refused.
 */
export function isAllowedLinkDeviceCallback(cb: unknown): boolean {
  if (typeof cb !== "string" || cb.length === 0 || cb.length > 2048) {
    return false;
  }
  if (cb !== cb.trim() || cb.includes(" ") || cb.includes("\t")) {
    return false;
  }
  if (!cb.toLowerCase().startsWith("creaton://")) return false;
  try {
    return new URL(cb).protocol.toLowerCase() === LINK_DEVICE_CB_SCHEME;
  } catch {
    return false;
  }
}

/**
 * Build the payload for one handoff. `nonce` must be the desktop's nonce
 * verbatim — the payload is bound to it — and `exp` is `nowMs` plus the
 * 5-minute lifetime.
 */
export function buildLinkDevicePayload(input: {
  secretKeyHex: string;
  nonce: string;
  nowMs?: number;
  ttlMs?: number;
}): LinkDevicePayload {
  const { secretKeyHex, nonce } = input;
  if (!PUBKEY_RE.test(secretKeyHex)) {
    throw new Error("secret key must be 64 hex characters");
  }
  if (!NONCE_RE.test(nonce)) {
    throw new Error("nonce must be 8-128 URL-safe characters");
  }
  const nowMs = input.nowMs ?? Date.now();
  const ttlMs = input.ttlMs ?? LINK_DEVICE_TTL_MS;
  return {
    v: LINK_DEVICE_PAYLOAD_VERSION,
    sk: secretKeyHex.toLowerCase(),
    nonce,
    exp: Math.floor((nowMs + ttlMs) / 1000),
  };
}

/** The payload as the exact JSON string that goes into the encryption. */
export function serializeLinkDevicePayload(payload: LinkDevicePayload): string {
  return JSON.stringify({
    v: payload.v,
    sk: payload.sk,
    nonce: payload.nonce,
    exp: payload.exp,
  });
}

function isLinkDevicePayload(value: unknown): value is LinkDevicePayload {
  if (typeof value !== "object" || value === null) return false;
  const keys = Object.keys(value);
  if (
    keys.length !== 4 ||
    !keys.includes("v") ||
    !keys.includes("sk") ||
    !keys.includes("nonce") ||
    !keys.includes("exp")
  ) {
    return false;
  }
  const p = value as Record<string, unknown>;
  return (
    p.v === LINK_DEVICE_PAYLOAD_VERSION &&
    typeof p.sk === "string" &&
    PUBKEY_RE.test(p.sk) &&
    typeof p.nonce === "string" &&
    NONCE_RE.test(p.nonce) &&
    typeof p.exp === "number" &&
    Number.isFinite(p.exp)
  );
}

/**
 * Parse the decrypted payload JSON. Refuses anything that is not exactly the
 * four documented fields with the right types — an extra field is as much a
 * protocol violation as a missing one.
 */
export function parseLinkDevicePayload(
  json: string,
): LinkDeviceResult<LinkDevicePayload> {
  let value: unknown;
  try {
    value = JSON.parse(json);
  } catch {
    return { ok: false, error: "malformed" };
  }
  if (!isLinkDevicePayload(value)) return { ok: false, error: "malformed" };
  return {
    ok: true,
    value: {
      v: value.v,
      sk: value.sk.toLowerCase(),
      nonce: value.nonce,
      exp: value.exp,
    },
  };
}

/**
 * Check a decrypted payload before adopting it: the nonce must be the one
 * this device generated (binding — anything else is a different session's
 * payload being replayed here) and `exp` must not be in the past.
 */
export function checkLinkDevicePayload(
  payload: LinkDevicePayload,
  options: { expectedNonce: string; nowMs?: number },
): LinkDeviceResult<LinkDevicePayload> {
  if (payload.nonce !== options.expectedNonce) {
    return { ok: false, error: "nonce-mismatch" };
  }
  const nowMs = options.nowMs ?? Date.now();
  if (payload.exp * 1000 < nowMs) {
    return { ok: false, error: "expired" };
  }
  return { ok: true, value: payload };
}

/**
 * Parse the handoff URL's query. Malformed parameters or a callback that is
 * not a `creaton://` URL are refused here so no caller can build a redirect
 * from them.
 */
export function parseLinkDeviceRequest(
  search: string | URLSearchParams,
): LinkDeviceResult<LinkDeviceRequest> {
  const params =
    typeof search === "string"
      ? new URLSearchParams(search.startsWith("?") ? search.slice(1) : search)
      : search;
  const pub = params.get("pub");
  const nonce = params.get("nonce");
  const cb = params.get("cb");
  if (!pub || !nonce || !cb) return { ok: false, error: "missing-param" };
  if (!PUBKEY_RE.test(pub)) return { ok: false, error: "bad-pubkey" };
  if (!NONCE_RE.test(nonce)) return { ok: false, error: "bad-nonce" };
  if (!isAllowedLinkDeviceCallback(cb)) {
    return { ok: false, error: "bad-callback" };
  }
  return {
    ok: true,
    value: { pub: pub.toLowerCase(), nonce, cb },
  };
}

/**
 * Append the encrypted payload and the sender's account pubkey to the
 * callback as `p` and `from`, with `p` wrapped in base64url so the URL stays
 * clean no matter what alphabet the cipher used. Throws on any callback that
 * is not `creaton://` — refusing here is what makes an arbitrary redirect
 * impossible even if a caller skips the URL parse.
 */
export function buildLinkDeviceCallback(
  cb: string,
  ciphertext: string,
  from: string,
): string {
  if (!isAllowedLinkDeviceCallback(cb)) {
    throw new Error("callback must be a creaton:// URL");
  }
  if (typeof ciphertext !== "string" || ciphertext.length === 0) {
    throw new Error("ciphertext must be a non-empty string");
  }
  if (typeof from !== "string" || !PUBKEY_RE.test(from)) {
    throw new Error("from must be the 64-hex account pubkey");
  }
  return `${cb}${cb.includes("?") ? "&" : "?"}p=${encodeBase64Url(ciphertext)}&from=${from.toLowerCase()}`;
}

/** The two redirect parameters a completed handoff carries. */
export type LinkDeviceCallback = {
  /** base64url of the NIP-44 payload. */
  p: string;
  /** Account pubkey the payload was sent from (64-hex, lowercase). */
  from: string;
};

/**
 * Parse a `<cb>?p=…&from=…` redirect. The ciphertext itself is opaque here
 * (it is only readable with the one-time secret key); this validates the
 * envelope so no caller reads a half-formed redirect.
 */
export function parseLinkDeviceCallback(
  search: string | URLSearchParams,
): LinkDeviceResult<LinkDeviceCallback> {
  const params =
    typeof search === "string"
      ? new URLSearchParams(search.startsWith("?") ? search.slice(1) : search)
      : search;
  const p = params.get("p");
  const from = params.get("from");
  if (!p || !from) return { ok: false, error: "missing-param" };
  if (!PUBKEY_RE.test(from)) return { ok: false, error: "bad-pubkey" };
  return { ok: true, value: { p, from: from.toLowerCase() } };
}
