//! Build-time template registry generator.
//!
//! Scans the repo-root `templates/` authoring directory and generates an
//! embedded registry (`$OUT_DIR/templates_registry.rs`) that `include_str!`s
//! every template file into the `buzz` binary, so the CLI works standalone
//! with no filesystem template directory at runtime.
//!
//! Why a generated registry (not manual `include_str!` lists or the
//! `include_dir` crate): template content is authored outside Rust, so a
//! generated registry means adding `templates/<id>/` is picked up on the next
//! build with **zero Rust edits** — no registry file for content authors to
//! forget. It also adds no new dependency. `cargo:rerun-if-changed` covers the
//! directory (adds/removes) and every file (content edits), so stale builds
//! cannot serve old content. The registry-completeness test in
//! `src/commands/templates/registry.rs` re-walks `templates/` at test time and
//! fails on any disk/registry drift.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let templates_dir = manifest_dir.join("..").join("..").join("templates");

    // Re-run when the directory itself changes (file adds/removes) and for
    // every existing file (content edits).
    println!("cargo:rerun-if-changed={}", templates_dir.display());

    let mut templates: Vec<(String, Vec<(String, PathBuf)>)> = Vec::new();
    if templates_dir.is_dir() {
        let mut dirs: Vec<PathBuf> = fs::read_dir(&templates_dir)
            .expect("read templates dir")
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.is_dir())
            .collect();
        dirs.sort();
        for dir in dirs {
            let dir_name = dir
                .file_name()
                .expect("template dir name")
                .to_string_lossy()
                .into_owned();
            let mut files = Vec::new();
            collect_files(&dir, &dir, &mut files);
            files.sort_by(|a, b| a.0.cmp(&b.0));
            templates.push((dir_name, files));
        }
    }
    templates.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::from(
        "// @generated by crates/buzz-cli/build.rs from the repo-root templates/ \
         directory — do not edit.\n",
    );
    out.push_str("pub static EMBEDDED_TEMPLATES: &[EmbeddedTemplate] = &[\n");
    for (dir_name, files) in &templates {
        out.push_str("    EmbeddedTemplate {\n");
        out.push_str(&format!("        dir: \"{}\",\n", escape(dir_name)));
        out.push_str("        files: &[\n");
        for (rel, abs) in files {
            println!("cargo:rerun-if-changed={}", abs.display());
            out.push_str("            EmbeddedFile {\n");
            out.push_str(&format!("                path: \"{}\",\n", escape(rel)));
            out.push_str(&format!(
                "                content: include_str!(r#\"{}\"#),\n",
                abs.display()
            ));
            out.push_str("            },\n");
        }
        out.push_str("        ],\n");
        out.push_str("    },\n");
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("templates_registry.rs"), out).expect("write templates_registry.rs");
}

/// Recursively collect `(relative_path, absolute_path)` for every file under `dir`.
fn collect_files(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.is_dir() {
            collect_files(root, &path, out);
        } else {
            let rel = path
                .strip_prefix(root)
                .expect("file under template root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push((rel, path));
        }
    }
}

/// Escape a string for use inside a Rust string literal.
fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
