// @generated by `just regen-kinds` (scripts/regen-kinds.mjs) — DO NOT EDIT.
// Source of truth: crates/buzz-core/src/kind.rs. Values and names are wire
// format: change the Rust registry, then run `just regen-kinds`.
// ignore_for_file: constant_identifier_names, doc_markdown, comment_references

/// Event-kind registry mirrored from the relay's Rust source of truth
/// (crates/buzz-core/src/kind.rs).
class Kinds {
  Kinds._();

  // Standard NIP kinds
  /// NIP-01: User profile metadata.
  static const int KIND_PROFILE = 0;

  /// NIP-01: Short text note.
  static const int KIND_TEXT_NOTE = 1;

  /// NIP-02: Contact list / follow list.
  static const int KIND_CONTACT_LIST = 3;

  /// NIP-51: Mute list (replaceable, 10000–19999 range) — pubkeys/events/threads/words a user has muted.
  ///
  /// User-owned global state, keyed by `(pubkey, kind)`. Same ownership/scope shape as kind:3.
  static const int KIND_MUTE_LIST = 10000;

  /// NIP-51: Pin list (replaceable) — events the user has pinned to their profile.
  ///
  /// User-owned global state, keyed by `(pubkey, kind)`. The events referenced may live in
  /// channels, but the pin list itself is profile-level state.
  static const int KIND_PIN_LIST = 10001;

  /// NIP-65: Relay list metadata (replaceable) — read/write relay preferences for the outbox model.
  ///
  /// User-owned global state, keyed by `(pubkey, kind)`. Tags are `["r", url]` or
  /// `["r", url, "read"]` / `["r", url, "write"]`.
  static const int KIND_NIP65_RELAY_LIST_METADATA = 10002;

  /// NIP-51: Bookmark list (replaceable) — events/articles/hashtags/URLs the user has bookmarked.
  ///
  /// User-owned global state, keyed by `(pubkey, kind)`. References content but is not itself
  /// channel-scoped content.
  static const int KIND_BOOKMARK_LIST = 10003;

  /// NIP-51: Emoji list (replaceable) — user preferred emojis and pointers to emoji sets.
  static const int KIND_EMOJI_LIST = 10030;

  /// NIP-51: Follow set (parameterized replaceable, 30000–39999 range) — named curated lists of pubkeys.
  ///
  /// User-owned, keyed by `(pubkey, kind, d_tag)`. Allows multiple named follow lists on top of
  /// the single kind:3 contact list (e.g. "close-friends", "news", "devs").
  static const int KIND_FOLLOW_SET = 30000;

  /// NIP-51: Bookmark set (parameterized replaceable) — named curated bookmark collections.
  ///
  /// User-owned, keyed by `(pubkey, kind, d_tag)`.
  static const int KIND_BOOKMARK_SET = 30003;

  /// NIP-51 / NIP-30: Emoji set (parameterized replaceable).
  ///
  /// User-owned, keyed by `(pubkey, kind, d_tag)`. Each member publishes their own
  /// kind:30030 set (signed as themselves); the workspace emoji "palette" is the
  /// client-side union of everyone's sets — a view computed on read, not stored
  /// state. Ingest allowlists member-authored kind:30030/10030 (see
  /// `required_scope_for_kind`), and the generic NIP-33 replace path keeps only the
  /// latest per `(pubkey, d_tag)`.
  static const int KIND_EMOJI_SET = 30030;

  /// NIP-01: Channel metadata (replaceable). Not used by Buzz today.
  static const int KIND_CHANNEL_METADATA = 41;

  /// NIP-09: Event deletion request.
  static const int KIND_DELETION = 5;

  /// NIP-25: Content is emoji char or `+`/`-`.
  static const int KIND_REACTION = 7;

  /// NIP-17: Outer envelope for private DMs — hides sender, content, timestamp.
  static const int KIND_GIFT_WRAP = 1059;

  /// NIP-94: File metadata attachment.
  static const int KIND_FILE_METADATA = 1063;

  /// NIP-23: Long-form content (articles, blog posts, RFCs).
  /// Parameterized replaceable (NIP-33, 30000–39999 range) — keyed by `(pubkey, kind, d_tag)`.
  /// Stored globally (channel_id = NULL); author-owned, not channel-scoped.
  static const int KIND_LONG_FORM = 30023;

  /// NIP-38: User status (general, music, or custom d-tag).
  /// Parameterized replaceable (NIP-33, 30000–39999 range) — keyed by `(pubkey, kind, d_tag)`.
  /// Stored globally (channel_id = NULL); user-owned personal data, not channel-scoped.
  static const int KIND_USER_STATUS = 30315;

  /// NIP-78 / NIP-RS: Per-client read state blob for cross-device read position sync.
  /// Parameterized replaceable (NIP-33, 30000–39999 range) — keyed by `(pubkey, kind, d_tag)`.
  /// Stored globally (channel_id = NULL); user-owned personal data, not channel-scoped.
  /// Content is NIP-44 encrypted to the user's own keypair.
  static const int KIND_READ_STATE = 30078;

  /// NIP-42 auth event — never stored (carries bearer tokens).
  static const int KIND_AUTH = 22242;

  /// BUD-01: Blossom upload auth (used in upload.rs, not stored).
  static const int KIND_BLOSSOM_AUTH = 24242;

  /// Buzz custom one-time identity binding proof (ephemeral, not stored).
  static const int KIND_NOSTR_IDENTITY_BINDING = 24243;

  /// NIP-98: HTTP auth event (used in nip98.rs, not stored).
  static const int KIND_HTTP_AUTH = 27235;

  // NEW: Buzz command kinds (Pure Nostr plan)
  /// Agent metadata + owner reference (replaceable, agent-authored).
  static const int KIND_AGENT_PROFILE = 10100;

  /// NIP-AE: Agent Engram (parameterized replaceable, agent-authored).
  ///
  /// Encrypted memory record for AI agents. Addressed by `(pubkey_a, kind, d_tag)`,
  /// where `d_tag` is an HMAC over the agent↔owner conversation key. See
  /// `docs/nips/NIP-AE.md` and [`crate::engram`].
  static const int KIND_AGENT_ENGRAM = 30174;

  /// NIP-ER: Event Reminder (parameterized replaceable, author-only).
  ///
  /// Encrypted, author-only reminder addressed by `(pubkey, kind, d_tag)`. The
  /// public `not_before` tag tells supporting relays when the reminder is due;
  /// the target, note, and state are NIP-44 encrypted to the author. Reads are
  /// author-only (see [`AUTHOR_ONLY_KINDS`]). See `docs/nips/NIP-ER.md`.
  static const int KIND_EVENT_REMINDER = 30300;

  /// NIP-PL: encrypted push lease (parameterized replaceable, author-only).
  ///
  /// The source event contains endpoint-bearing NIP-44 ciphertext and is readable
  /// only by its authenticated author. Effective delivery state lives in the
  /// dedicated push lease tables.
  static const int KIND_PUSH_LEASE = 30350;

  /// NIP-PMA: owner-encrypted private managed-agent aggregate.
  ///
  /// Addressed by `(owner pubkey, kind, agent pubkey)`. The signed outer tags
  /// expose only the agent coordinate, CAS generation/predecessor, and active/deleted
  /// state required for relay enforcement. Content is NIP-44 v2 encrypted from
  /// the owner's key to itself and contains the runnable identity/configuration
  /// plus exact public projection bindings. See `docs/nips/NIP-PMA.md`.
  static const int KIND_PRIVATE_MANAGED_AGENT = 30179;

  /// Agent skill definition — a shareable instruction set following the Agent
  /// Skills format (`skills/<name>/SKILL.md` with YAML frontmatter, see
  /// `crates/buzz-persona/PERSONA_PACK_SPEC.md` §6).
  ///
  /// This NIP claims `kind:30180`. It is in the NIP-33 parameterized
  /// replaceable range (30000–39999) per NIP-01: addressed by
  /// `(pubkey, kind, d_tag)` where `d` is the skill's stable id, with only the
  /// latest event per address retained. Community-level and global-only — a
  /// stray `h` never channel-scopes it, matching the persona family.
  ///
  /// Content is a JSON body: `{"name", "description", "sha256", "content",
  /// "attachments"}`. `name`/`description` are the canonical identity fields
  /// taken from the SKILL.md frontmatter (the harness load key), `content` is
  /// the full SKILL.md text, and `sha256` pins those exact bytes. `attachments`
  /// is the folder-growth extension point: reserved for hash-pinned companion
  /// files (`scripts/`, `references/`, `assets/`) as records shaped
  /// `{"role", "path", "content_type", "sha256", "source"}` — v1 writers emit
  /// an empty array and v1 readers accept its absence.
  ///
  /// Template applies bind skills to agents with `["skill", "<skill-id>",
  /// "developers"|"all"]` tags on the agent's persona events (kind:30175);
  /// the third element records the inheritance scope verbatim.
  ///
  /// Distinct from the channel-scoped company-brain skill catalog (kind 45011,
  /// planned on the dao-launchpad line): that kind stores loose markdown
  /// catalog entries per channel, while this kind is the globally-keyed,
  /// frontmatter-validated Agent Skills definition.
  static const int KIND_SKILL = 30180;

  /// NIP-AP: Agent Persona (parameterized replaceable, owner-authored).
  ///
  /// Persona definition event published by the workspace owner. Addressed by
  /// `(pubkey, kind, d_tag)` where `d_tag` is the plaintext persona slug.
  /// Content is a JSON body containing persona fields (system_prompt,
  /// display_name, avatar_url, runtime, model, provider, name_pool).
  ///
  /// # Access control: author-only-unless-shared
  ///
  /// Kind 30175 uses **shared-tag-gated** read semantics to protect system
  /// prompts and `respond_to_allowlist` pubkeys from being visible to all
  /// community members as a side-effect of device sync:
  ///
  /// - Events WITHOUT a `["shared", "true"]` tag are readable only by their
  ///   author. Foreign REQ/COUNT/fan-out/ids-lookup requests silently omit them.
  /// - Events WITH exactly `["shared", "true"]` are readable community-wide,
  ///   enabling the opt-in agent catalog (`{kinds:[30175]}` all-authors).
  ///
  /// Device sync already queries `authors:[self]`, so this gate never affects
  /// self-reads. The `shared` tag is a tag (not a content field) so toggling
  /// sharing does not change content bytes or the drift/`source_version` hash
  /// (`persona_content_hash`) used by persona sync.
  ///
  /// Ingest rejects malformed `shared` tags (any value other than `"true"`,
  /// or more than one `shared` tag) so no ambiguous heads can exist.
  static const int KIND_PERSONA = 30175;

  /// NIP-AP: Agent Team (parameterized replaceable, owner-authored).
  ///
  /// Team definition event published by the workspace owner. Addressed by
  /// `(pubkey, kind, d_tag)` where `d_tag` is the team's stable id. Content is a
  /// JSON body projecting public team fields (name, description, persona_ids).
  /// A team is a user-facing grouping of personas; publishing keeps it
  /// authoritative across clients and reboots, mirroring `KIND_PERSONA`.
  static const int KIND_TEAM = 30176;

  /// NIP-AP: Managed Agent (parameterized replaceable, owner-authored).
  ///
  /// Managed-agent definition event published by the workspace owner. Addressed
  /// by `(pubkey, kind, d_tag)` where `d_tag` is the agent's pubkey. Content is
  /// an explicit opt-IN allowlist projection of the agent record — it MUST never
  /// carry the agent's secret key, NIP-OA auth tag, env vars, or runtime fields,
  /// since these events are world-readable on the relay.
  static const int KIND_MANAGED_AGENT = 30177;

  /// NIP-AP: Team Catalog projection (parameterized replaceable, owner-authored).
  ///
  /// The shareable projection of a team, addressed by `(pubkey, kind, d_tag)`
  /// where `d_tag` is the team's stable id. Content is a versioned JSON body
  /// carrying sanitized team fields plus ordered, EMBEDDED member definition
  /// projections.
  ///
  /// # Why this is not a `shared` tag on [`KIND_TEAM`]
  ///
  /// A team's members live in kind 30175 events that are author-only unless
  /// individually shared, so a foreign reader of a shared team could never
  /// hydrate its members. This kind therefore embeds the member projections
  /// rather than referencing them: the share is atomic, it covers built-in
  /// members that have no 30175 head at all, it is immune to local-id/d-tag
  /// divergence, and an unshared 30175 stays private. Kind 30176's wire body is
  /// untouched, so device sync keeps its contract.
  ///
  /// # Access control
  ///
  /// Member of [`SHARED_GATED_KINDS`]: author-only unless the event carries
  /// exactly `["shared", "true"]`. Ingest additionally requires exactly one
  /// non-empty, bounded `d` tag — generic NIP-33 storage maps a missing `d` to
  /// the empty coordinate, which would collapse every team into one slot.
  ///
  /// Content carries only sanitized fields: no env vars, no `respond_to`
  /// allowlist pubkeys, no source or local ids, no filesystem paths, no secrets.
  static const int KIND_TEAM_CATALOG = 30178;

  // NIP-56 reporting
  /// NIP-56: Report an event, pubkey, or blob to relay moderators (kind:1984).
  ///
  /// Accepted at ingest, persisted to the tenant-scoped `moderation_reports`
  /// queue, and never fanned out publicly. Reports are signals, not triggers:
  /// the relay never auto-actions on them (NIP-56).
  static const int KIND_REPORT = 1984;

  /// Buzz product feedback submission. Accepted at ingest, sidecarred to the
  /// deployment feedback table, and never stored or fanned out as an event.
  static const int KIND_PRODUCT_FEEDBACK = 42000;

  // NIP-29 group admin events
  /// NIP-29: Add a user to a group.
  static const int KIND_NIP29_PUT_USER = 9000;

  /// NIP-29: Remove a user from a group.
  static const int KIND_NIP29_REMOVE_USER = 9001;

  /// NIP-29: Edit group metadata.
  static const int KIND_NIP29_EDIT_METADATA = 9002;

  /// NIP-29: Delete an event from a group.
  static const int KIND_NIP29_DELETE_EVENT = 9005;

  /// NIP-29: Create a new group.
  static const int KIND_NIP29_CREATE_GROUP = 9007;

  /// NIP-29: Delete a group.
  static const int KIND_NIP29_DELETE_GROUP = 9008;

  /// NIP-29: Create an invite to a group.
  static const int KIND_NIP29_CREATE_INVITE = 9009;

  /// NIP-29: Request to join a group.
  static const int KIND_NIP29_JOIN_REQUEST = 9021;

  /// NIP-29: Request to leave a group.
  static const int KIND_NIP29_LEAVE_REQUEST = 9022;

  // Buzz community moderation commands (mod-signed, processed like 9030-series:
  // validated + executed directly, never stored as regular events; every
  // accepted command writes a `moderation_actions` audit row).
  /// Moderation: ban a pubkey from the community (`p` tag target, optional
  /// `expiration` + `reason` tags).
  static const int KIND_MODERATION_BAN = 9040;

  /// Moderation: lift a community ban (`p` tag target).
  static const int KIND_MODERATION_UNBAN = 9041;

  /// Moderation: timeout (write-block) a pubkey until an `expiration` tag
  /// timestamp (`p` tag target, optional `reason`).
  static const int KIND_MODERATION_TIMEOUT = 9042;

  /// Moderation: clear a timeout early (`p` tag target).
  static const int KIND_MODERATION_UNTIMEOUT = 9043;

  /// Moderation: resolve a report (`report` tag = report event id hex,
  /// `status` tag = resolved|dismissed, `action` tag =
  /// delete|kick|ban|timeout|dismiss|escalate — see
  /// `handlers/moderation_commands.rs` for the pinned vocabulary).
  static const int KIND_MODERATION_RESOLVE_REPORT = 9044;

  // NIP-43 relay membership announcement events (relay-signed)
  /// NIP-43: Relay membership list snapshot (relay-signed, replaceable by convention).
  static const int KIND_NIP43_MEMBERSHIP_LIST = 13534;

  /// NIP-43: Member added announcement (relay-signed).
  static const int KIND_NIP43_MEMBER_ADDED = 8000;

  /// NIP-43: Member removed announcement (relay-signed).
  static const int KIND_NIP43_MEMBER_REMOVED = 8001;

  /// NIP-43: User leave request (user-signed, ephemeral).
  static const int KIND_NIP43_LEAVE_REQUEST = 28936;

  // NIP-IA identity archival requests (user/agent/owner-signed)
  /// NIP-IA: Request that the relay archive a target identity.
  static const int KIND_IA_ARCHIVE_REQUEST = 9035;

  /// NIP-IA: Request that the relay unarchive a target identity.
  static const int KIND_IA_UNARCHIVE_REQUEST = 9036;

  // NIP-IA identity archival announcement events (relay-signed)
  /// NIP-IA: Archived-identity delta (relay-signed).
  static const int KIND_IA_ARCHIVED = 8002;

  /// NIP-IA: Unarchived-identity delta (relay-signed).
  static const int KIND_IA_UNARCHIVED = 8003;

  /// NIP-IA: Archived identities list snapshot (relay-signed, replaceable).
  static const int KIND_IA_ARCHIVED_LIST = 13535;

  // NIP-29 group state (addressable range 39000–39003)
  /// NIP-29: Addressable group metadata state.
  static const int KIND_NIP29_GROUP_METADATA = 39000;

  /// NIP-29: Addressable group admins list.
  static const int KIND_NIP29_GROUP_ADMINS = 39001;

  /// NIP-29: Addressable group members list.
  static const int KIND_NIP29_GROUP_MEMBERS = 39002;

  /// NIP-29: Addressable group roles definition.
  static const int KIND_NIP29_GROUP_ROLES = 39003;

  // Channel-window overlays (relay-signed, synthesized at query time, never
  // stored). Appended to bridge `/query` responses for `top_level` window
  // requests — see docs/bridge-channel-window.md.
  /// Thread summary overlay: `e`/`d` tag = root event id, content =
  /// `{reply_count, descendant_count, last_reply_at, participants}`.
  static const int KIND_THREAD_SUMMARY = 39005;

  /// Window bounds overlay: `d` tag = `<channel_id>:<request-cursor-or-head>`,
  /// content = `{has_more, next_cursor}`. The only authority on exhaustion —
  /// clients must not infer `has_more` from row counts.
  static const int KIND_WINDOW_BOUNDS = 39006;

  /// NIP-CW thread-mode query-time bounds, bound to a normalized newest-first thread request.
  static const int KIND_THREAD_WINDOW_BOUNDS = 39007;

  /// Workflow definition (parameterized replaceable, d=workflow_uuid).
  static const int KIND_WORKFLOW_DEF = 30620;

  /// NIP-DV: per-viewer DM visibility snapshot (relay-signed, parameterized
  /// replaceable, d=viewer_pubkey). Carries one `h` tag per DM the viewer has
  /// hidden from their sidebar. Re-published by the relay on every hide/unhide so
  /// the latest event is always the authoritative hidden set. The relay knows
  /// `hidden_at` per viewer; this is the only Nostr-visible projection of it.
  static const int KIND_DM_VISIBILITY = 30622;

  // Ephemeral events (20000–29999) — Redis pub/sub only, never stored.
  /// Ephemeral: user presence update (online/away/offline).
  static const int KIND_PRESENCE_UPDATE = 20001;

  /// NIP-AB: Device pairing event. Ephemeral — relay may discard after delivery.
  static const int KIND_PAIRING = 24134;

  /// Ephemeral: typing indicator for a channel.
  static const int KIND_TYPING_INDICATOR = 20002;

  /// Ephemeral: live wiki co-editing sync (human wiki pages, kind:44001).
  ///
  /// Content is base64 of a Yjs sync/update message. A `d` tag names the page
  /// slug; an `h` tag may scope the event to a channel. The relay fans the
  /// event out to live subscribers and never stores it — offline peers converge
  /// from the newest saved revision (kind:44001) on next open instead.
  static const int KIND_WIKI_SYNC = 20003;

  /// Ephemeral: owner-scoped encrypted agent observer telemetry and control frame.
  static const int KIND_AGENT_OBSERVER_FRAME = 24200;

  /// Ephemeral: huddle emoji reaction burst. Channel-scoped to the ephemeral
  /// huddle channel with an `h` tag; never stored in the timeline.
  static const int KIND_HUDDLE_REACTION = 24810;

  // Stream messaging
  /// NIP-29 group chat message kind. V1 used kind:10001 (replaceable range — wrong), then 40001.
  ///
  /// Agent shutdown convention: the agent's owner sends a kind:9 message with content
  /// `"!shutdown"` and a `#p` tag mentioning the agent. The harness exits gracefully.
  /// This is a convention, not a new event kind — uses regular stream messages.
  static const int KIND_STREAM_MESSAGE = 9;

  /// V1 used kind:10002 (replaceable range — wrong).
  static const int KIND_STREAM_MESSAGE_V2 = 40002;

  /// V1 used kind:10004 (replaceable range + NIP-51 collision — wrong).
  static const int KIND_STREAM_MESSAGE_EDIT = 40003;

  /// A reminder attached to a stream message or time.
  static const int KIND_STREAM_REMINDER = 40007;

  /// A diff/patch message showing file changes (unified diff format).
  static const int KIND_STREAM_MESSAGE_DIFF = 40008;

  /// Canvas (shared document) for a channel.
  static const int KIND_CANVAS = 40100;

  /// System message for channel state changes (join, leave, rename, etc.).
  static const int KIND_SYSTEM_MESSAGE = 40099;

  // Relay-only sidecar kinds (never client-submitted)
  /// Channel metadata with computed fields (relay-signed sidecar).
  static const int KIND_CHANNEL_SUMMARY = 40901;

  /// Bulk presence state (relay-signed sidecar).
  static const int KIND_PRESENCE_SNAPSHOT = 40902;

  // Direct messages (41000–41999)
  /// Open/create DM (p-tags = participants).
  static const int KIND_DM_OPEN = 41010;

  /// Add member to group DM.
  static const int KIND_DM_ADD_MEMBER = 41011;

  /// Hide DM from sidebar.
  static const int KIND_DM_HIDE = 41012;

  /// A new direct-message conversation was created.
  static const int KIND_DM_CREATED = 41001;

  // Agent job protocol (43000–43999)
  // Not using NIP-90 kinds (5000–6999) — Buzz requires auth chains (depth ≤ 3, breadth ≤ 10).
  /// An agent job was requested.
  static const int KIND_JOB_REQUEST = 43001;

  /// An agent accepted a job request.
  static const int KIND_JOB_ACCEPTED = 43002;

  /// Progress update for an in-flight agent job.
  static const int KIND_JOB_PROGRESS = 43003;

  /// Final result of a completed agent job.
  static const int KIND_JOB_RESULT = 43004;

  /// A job cancellation was requested.
  static const int KIND_JOB_CANCEL = 43005;

  /// An agent job failed with an error.
  static const int KIND_JOB_ERROR = 43006;

  /// Relay-signed notification: the target pubkey was added to a channel.
  /// Stored globally (channel_id = None) with p-tag = target, h-tag = channel UUID.
  static const int KIND_MEMBER_ADDED_NOTIFICATION = 44100;

  /// Relay-signed notification: the target pubkey was removed from a channel.
  /// Stored globally (channel_id = None) with p-tag = target, h-tag = channel UUID.
  static const int KIND_MEMBER_REMOVED_NOTIFICATION = 44101;

  /// NIP-AM: Agent Turn Metric — durable per-turn token-usage record (agent-authored).
  ///
  /// Regular stored event (append-only, never replaced). The agent publishes one
  /// event per completed turn, NIP-44 encrypted to its owner. Tags: exactly one `p`
  /// (owner pubkey) and one `agent` (agent pubkey == event pubkey); no `h` tag.
  /// Stored globally (channel_id = NULL); owner-scoped reads only (p-gated, NIP-42).
  /// See `docs/nips/NIP-AM.md`.
  static const int KIND_AGENT_TURN_METRIC = 44200;

  // Agent fleet (44010–44019) — cooperation plane for multi-agent fleets.
  /// Fleet: an agent's capabilities advertisement (addressable, agent-authored).
  ///
  /// Addressed by `d` = stable agent id (pubkey by default). Content is JSON:
  /// `{ "name": string, "runtype": "browser"|"desktop"|"sandbox", "status":
  /// "available"|"busy"|"offline", "tools": string[], "heartbeat": unix_sec }`.
  /// The live fleet roster is a subscription over this kind; liveness is
  /// heartbeat recency, so agents refresh this event periodically.
  static const int KIND_AGENT_CAPABILITIES = 44010;

  /// Fleet: a coordination task (addressable).
  ///
  /// Addressed by `d` = task id. Content is JSON:
  /// `{ "title": string, "description": string, "status":
  /// "open"|"assigned"|"in_progress"|"needs_approval"|"done"|"cancelled" }`.
  /// `p` tag = assignee pubkey, `e` tag = parent task/thread. Approvals reuse
  /// the workflow approval kinds; any fleet member may pick up an open task.
  static const int KIND_AGENT_TASK = 44011;

  /// Team: a teamwork strategy definition (addressable, `d` = strategy id).
  ///
  /// Content is JSON:
  /// `{ "v": 1, "name": string, "description": string, "teamworkPrompt":
  /// string, "roles": { "<slot>": "<role prompt>" }, "steps": [{ "participants":
  /// ["<slot>", ...], "rounds": int, "flow": "local"|"summary", "prompt":
  /// string, "perAgentPrompts"?: { "<slot>": string } }], "finalWriter":
  /// "<slot>" }`. Slots are persistent roster positions shared by the whole
  /// strategy; `steps` are the ordered conversational phases. Bounded at
  /// ingest (sizes, participant/phase/round caps); semantics validated by the
  /// CLI before a run.
  static const int KIND_TEAM_STRATEGY = 44020;

  /// Team: one executed run of a strategy (addressable, `d` = run id).
  ///
  /// Content is JSON:
  /// `{ "v": 1, "strategyId": string, "problem": string, "transcript":
  /// [{ "phase": int, "agentSlot": string, "content": string, "tokens": int }],
  /// "finalAnswer": string, "totalTokens": int, "model": string, "status":
  /// "complete" }`. The transcript rows mirror the kind:44022 turn events so a
  /// reader can reconstruct the run from a single event; the turn events carry
  /// the same content as durable per-turn records.
  static const int KIND_TEAM_RUN = 44021;

  /// Team: one conversational turn of a run (addressable, `d` =
  /// `<run-id>/<phase>/<agentSlot>`). Content is markdown: the agent's turn,
  /// the summary digest of a summary-flow phase, or the final writer's
  /// certificate.
  static const int KIND_TEAM_TURN = 44022;

  // Wiki (44001) — community knowledge base pages.
  /// A wiki page (addressable, NIP-33): `d` tag = page slug, content = markdown.
  /// The community brain in the web client: humans and agents read/write the
  /// same pages through the relay data plane.
  static const int KIND_WIKI_PAGE = 44001;

  // Agent Wiki (44002) — agent-maintained knowledge base pages.
  /// An agent-maintained wiki page (addressable, `d` = `<space>/<slug>`, content
  /// = markdown) — the Agent Wiki: a distinct feature from the human wiki
  /// (kind:44001, Yjs/Trystero live editing). One page per space is the
  /// executive standup (`<space>/standup`), rewritten to current truth by the
  /// distillation loop; further `<space>/<slug>` pages are durable knowledge.
  ///
  /// Community-level, global-only (same addressing model as the NIP-ORG kinds):
  /// keyed by `(pubkey, kind, d_tag)`, never channel-scoped by a stray `h` tag.
  ///
  /// Provenance tags (all bounded at ingest): `model` (the model that produced
  /// the page), `cost_tokens` (token usage of the distillation), and `sources`
  /// (comma-separated source event ids the page was distilled from).
  ///
  /// 44002 is outside the NIP-33 parameterized-replaceable range (30000–39999),
  /// so the relay stores every revision as a regular event (same as kind:44001):
  /// replacement is read-side LWW — readers take the newest event per
  /// `(pubkey, kind, d_tag)`.
  static const int KIND_AGENT_WIKI_PAGE = 44002;

  // Wiki corrections (44003) — member "Suggest a correction" notes.
  /// A member's correction suggestion for a wiki page (addressable, content =
  /// markdown). Any member may publish one; the distillation loop folds
  /// unconsumed corrections into the next page revision as untrusted data.
  ///
  /// Pinned shape: exactly one `d` tag shaped `correction-for-<slug>` plus one
  /// `t` tag shaped `correction-for:<slug>` naming the same slug. Corrections
  /// are per-AUTHOR coordinates (`44003:<author>:correction-for-<slug>`) —
  /// deletion is scoped to the signer's own correction and must never touch
  /// another author's. A correction never participates in the slug-wide page
  /// deletion of kinds 44001/44002.
  ///
  /// Outside the NIP-33 parameterized-replaceable range (30000–39999): every
  /// revision is stored and replacement is read-side LWW per
  /// `(pubkey, kind, d_tag)`, exactly like kinds 44001/44002.
  static const int KIND_WIKI_CORRECTION = 44003;

  // Forum / social (45000–45999)
  // V1 used addressable range (30001–30003) — wrong.
  /// A forum post (thread root).
  static const int KIND_FORUM_POST = 45001;

  /// NIP-AR complete artifact revision.
  static const int KIND_ARTIFACT = 45010;

  /// Relay-authenticated artifact removal.
  static const int KIND_ARTIFACT_REMOVAL = 45011;

  /// A vote on a forum post.
  static const int KIND_FORUM_VOTE = 45002;

  /// A comment reply on a forum post.
  static const int KIND_FORUM_COMMENT = 45003;

  // Workflow engine (46000–46999)
  /// Trigger workflow execution.
  static const int KIND_WORKFLOW_TRIGGER = 46020;

  /// Grant pending approval.
  static const int KIND_APPROVAL_GRANT = 46030;

  /// Deny pending approval.
  static const int KIND_APPROVAL_DENY = 46031;

  /// A workflow was triggered by a matching event.
  static const int KIND_WORKFLOW_TRIGGERED = 46001;

  /// A workflow step began execution.
  static const int KIND_WORKFLOW_STEP_STARTED = 46002;

  /// A workflow step completed successfully.
  static const int KIND_WORKFLOW_STEP_COMPLETED = 46003;

  /// A workflow step failed.
  static const int KIND_WORKFLOW_STEP_FAILED = 46004;

  /// The entire workflow completed successfully.
  static const int KIND_WORKFLOW_COMPLETED = 46005;

  /// The entire workflow failed.
  static const int KIND_WORKFLOW_FAILED = 46006;

  /// The workflow was cancelled before completion.
  static const int KIND_WORKFLOW_CANCELLED = 46007;

  /// A workflow step is waiting for human approval.
  static const int KIND_WORKFLOW_APPROVAL_REQUESTED = 46010;

  /// A pending workflow approval was granted.
  static const int KIND_WORKFLOW_APPROVAL_GRANTED = 46011;

  /// A pending workflow approval was denied.
  static const int KIND_WORKFLOW_APPROVAL_DENIED = 46012;

  // System / admin custom range (48000–48999)
  /// An audit log entry was recorded.
  static const int KIND_AUDIT_ENTRY = 48001;

  /// A huddle (audio/video session) was started.
  static const int KIND_HUDDLE_STARTED = 48100;

  /// A participant joined a huddle.
  static const int KIND_HUDDLE_PARTICIPANT_JOINED = 48101;

  /// A participant left a huddle.
  static const int KIND_HUDDLE_PARTICIPANT_LEFT = 48102;

  /// A huddle ended.
  static const int KIND_HUDDLE_ENDED = 48103;

  /// Relay-synthesized authoritative liveness for an active huddle session.
  static const int KIND_HUDDLE_LIVENESS = 48104;

  /// Huddle channel guidelines/rules document.
  static const int KIND_HUDDLE_GUIDELINES = 48106;

  // Media (49000–49999)
  /// Internal kind for media upload audit entries. Not a relay event kind.
  static const int KIND_MEDIA_UPLOAD = 49001;

  /// NIP-34: Repository announcement (parameterized replaceable, d-tag = repo-id).
  static const int KIND_GIT_REPO_ANNOUNCEMENT = 30617;

  /// NIP-34: Repository state — current branch/tag refs (parameterized replaceable, d-tag = repo-id).
  static const int KIND_GIT_REPO_STATE = 30618;

  /// NIP-34: Patch (git format-patch output).
  static const int KIND_GIT_PATCH = 1617;

  /// NIP-34: Pull request.
  static const int KIND_GIT_PULL_REQUEST = 1618;

  /// NIP-34: Pull request update (tip commit change).
  static const int KIND_GIT_PR_UPDATE = 1619;

  /// NIP-34: Issue.
  static const int KIND_GIT_ISSUE = 1621;

  /// NIP-34: Status — Open.
  static const int KIND_GIT_STATUS_OPEN = 1630;

  /// NIP-34: Status — Applied / Merged.
  static const int KIND_GIT_STATUS_MERGED = 1631;

  /// NIP-34: Status — Closed.
  static const int KIND_GIT_STATUS_CLOSED = 1632;

  /// NIP-34: Status — Draft.
  static const int KIND_GIT_STATUS_DRAFT = 1633;

  /// NIP-MP: Multi-repo project — a named grouping of `kind:30617` repository
  /// announcements (parameterized replaceable, d=project slug).
  ///
  /// Members are `a` tags holding `30617:<owner-hex>:<repo-d>` coordinates, so one
  /// project may span repositories owned by different pubkeys. The signer gains no
  /// authority over any member: push policy reads the repository's own
  /// announcement, never a project. See `docs/nips/NIP-MP.md`.
  static const int KIND_PROJECT = 30621;

  /// NIP-LP: DAO launch record — a named fundraise with a community link, chain
  /// addresses, and an auction parameter commitment (parameterized replaceable,
  /// d = launch id). One signer; grouping assertions only, no authority over
  /// linked projects, repositories, or channels. See `docs/nips/NIP-LP.md`.
  static const int KIND_LAUNCH_RECORD = 37001;

  /// NIP-LP: auction bid mirror (regular). Advisory — the chain is authoritative.
  static const int KIND_LAUNCH_BID = 47002;

  /// NIP-LP: founder-signed launch update (regular).
  static const int KIND_LAUNCH_UPDATE = 47003;

  /// NIP-LP: proposal record — plain, futarchy-budget, or signal (regular).
  static const int KIND_LAUNCH_PROPOSAL = 47004;

  /// NIP-LP: chain-state receipt mirror (regular). Advisory.
  static const int KIND_LAUNCH_RECEIPT = 47005;

  /// NIP-LP: royalty schedule mirror (regular). Advisory — the chain is
  /// authoritative. Published when `ClaimStake` mints a schedule in the
  /// launch's RoyaltyDistributor. See `docs/token-lifecycle-design.md`.
  static const int KIND_ROYALTY_SCHEDULE = 47006;

  /// NIP-LP: royalty settlement-close mirror (regular). Advisory. One event
  /// per closed settlement window (revenue, shares, pool, carry).
  static const int KIND_ROYALTY_CLOSE = 47007;

  /// NIP-LP: trustgraph score root (parameterized replaceable, d = program:epoch).
  /// Published by a scoring operator with its Merkle root and proof pointer;
  /// clients verify individual score claims against the root without a prover.
  static const int KIND_SCORE_ROOT = 37006;

  /// NIP-ORG: org node — a role or team in a community's org chart
  /// (parameterized replaceable, d = node id). Community-level and
  /// global-only: addressed by `(pubkey, kind, d)` with no routing tag — a
  /// stray `h` never channel-scopes it. Roles are seats humans and agents
  /// hold; `parent` links form the hierarchy. See `docs/nips/NIP-ORG.md`.
  static const int KIND_ORG_NODE = 37010;

  /// NIP-ORG: org grant — a signed, scoped, revocable delegation of authority
  /// (parameterized replaceable, d = grant id). Community-level and
  /// global-only, no routing tag. Chains attenuate: each link conveys a
  /// subset of its parent. See `docs/nips/NIP-ORG.md`.
  static const int KIND_ORG_GRANT = 37011;

  /// NIP-ORG: budget — a bound on an agent's or delegated scope's autonomous
  /// action (parameterized replaceable, d = subject id). Community-level and
  /// global-only, no routing tag. Bounds autonomy, never a human's own
  /// actions. See `docs/nips/NIP-ORG.md`.
  static const int KIND_ORG_BUDGET = 37012;

  /// NIP-ORG: contribution record — a verified action with a multi-dimensional
  /// profile, evidence, human-vs-AI attribution, and `informed-by` chain for
  /// credit settlement (parameterized replaceable, d = action id).
  /// Community-level and global-only, no routing tag. See
  /// `docs/nips/NIP-ORG.md`.
  static const int KIND_CONTRIBUTION_RECORD = 37013;

  /// NIP-ORG: budget spend receipt — the Nostr mirror of a spend settled against
  /// an onchain allowance bound to a kind:37012 budget (parameterized
  /// replaceable, d = spend id). Community-level and global-only, no routing
  /// tag. Advisory: the contract is the ledger, Nostr the record (NIP-LP rule).
  /// See `docs/nips/NIP-ORG.md`.
  static const int KIND_BUDGET_SPEND_RECEIPT = 37014;

  /// NIP-ORG (Project Board): project pitch / team manifest — the board-facing
  /// pitch of a project (one-line summary, description, and the declared roles
  /// with their equity targets as `["role", <slug>, <label>, <pct>]` tags).
  /// Parameterized replaceable, `d` = the project's org-node id (same id as its
  /// kind:37010 node), so node and pitch replace together under one address.
  /// Community-level and global-only, no routing tag — a stray `h` never
  /// channel-scopes it. The org node carries the seat structure; this record
  /// carries the prose and the ownership declaration the board renders.
  static const int KIND_ORG_PITCH = 37015;

  /// NIP-ORG (Project Board): project join request — a signed request from a
  /// member to fill one declared role for a stated equity percentage.
  /// Parameterized replaceable, `d` = `<node>/<role>/<requester-16>` so each
  /// requester's thread has its own coordinate. The founder records a decline
  /// by republishing the same `d` under their own key with
  /// `content.decision = "declined"` — the NIP-ORG kind:37013 parallel-record
  /// pattern; approval is *not* an event here, it is the kind:37011 ownership
  /// grant (`["org", <pct>]` + `["role", <slug>]`), which is the canonical
  /// equity record. Community-level and global-only, no routing tag.
  static const int KIND_ORG_JOIN_REQUEST = 37016;

  /// NIP-ORG (Discovery plane): EVM binding record — "which address holds this
  /// seat", answerable from signed events alone (parameterized replaceable,
  /// `d` = the bound address). Community-level and global-only, no routing tag.
  ///
  /// # Wire contract (CONSUMED BY CLIENTS — do not change without updating
  /// producers)
  ///
  /// ```json
  /// {
  ///   "v": 1,
  ///   "address": "0x…",
  ///   "siweMessageHash": "0x…",
  ///   "attestation": <EIP-712 envelope> | null,
  ///   "revoked": true
  /// }
  /// ```
  ///
  /// - `d` — exactly one tag, lowercase `0x` + 40 hex of the bound EVM address.
  /// - Tags — exactly one `["address", "0x…"]` (checksummed or lowercase;
  ///   must equal `d` case-insensitively), and optionally exactly one
  ///   `["chain", "<EIP-155 chain id>"]` (decimal; when an attestation is
  ///   present it MUST equal `attestation.domain.chain_id`).
  /// - `content.v` — `1`.
  /// - `content.address` — same address as `d` (any case; compared as bytes).
  /// - `content.siweMessageHash` — `0x` + 64 hex: the EIP-191
  ///   `personal_sign` digest of the SIWE message the relay verified at bind
  ///   time (`buzz_evm_auth::personal_sign_digest`). A commitment/pointer a
  ///   client that holds the message can re-derive; ingest checks its shape
  ///   only (see below).
  /// - `content.attestation` — the EIP-712 `NostrSigner` envelope exactly as
  ///   `POST /auth/siwe/register` stores it (`buzz_evm_auth::AttestationEnvelope`:
  ///   `{"attestation":{"account","npub","expires","nonce"},"domain":{…},"signature"}`),
  ///   or `null` on a revocation.
  /// - `content.revoked` — optional boolean. `true` revokes the binding.
  ///
  /// **Authorship**: the event MUST be signed by the bound npub itself — the
  /// record claims *the author* holds `d`, never a third party.
  ///
  /// **Ingest enforcement (anti-spoof, fully offline — no RPC)**: for a live
  /// (non-revoked) record the `attestation` is REQUIRED and verified with
  /// `AttestationEnvelope::verify_for_npub(author, now)` — EIP-712 signature
  /// over the domain-separated digest, `attestation.npub` == event signer,
  /// not expired — and `attestation.account` MUST equal `content.address`
  /// (== `d`). A claim without that proof never lands. The SIWE leg
  /// (`siweMessageHash`) CANNOT be re-verified at ingest: the record carries
  /// only a hash, not the EIP-4361 message + `personal_sign` signature, so
  /// ingest does not pretend to check it — the attestation is the proof.
  ///
  /// **Revocation**: same `(author, d)` republished with `content.revoked:
  /// true` (NIP-ORG kind:37011 §Revocation — "republication of the same
  /// `(issuer, d)` with `revoked: true`"). NIP-33 LWW makes it the head. A
  /// revoked record needs no attestation — withdrawal requires only control
  /// of the npub, mirroring `POST /auth/siwe/revoke` (a kind:27235 npub
  /// proof, no EVM signature). When an attestation IS present on a revoked
  /// record it must still verify signature/npub/account; expiry is not
  /// enforced on withdrawal.
  ///
  /// **Reader rule**: resolve per `(author, d)` — the newest event of that
  /// coordinate wins (ties → lowest id); a foreign author's record for the
  /// same `d` never suppresses or replaces an author's own head.
  static const int KIND_EVM_BINDING = 37017;

  /// NIP-ORG (Discovery plane): deployment record — "where is the Summoner"
  /// (parameterized replaceable, `d` = `<chainId>:<role>`). Community-level
  /// and global-only, no routing tag — a stray `h` never channel-scopes it.
  ///
  /// # Wire contract (CONSUMED BY CLIENTS — do not change without updating
  /// producers)
  ///
  /// ```json
  /// { "v": 1, "block": 123, "project": "<slug>", "note": "…" }
  /// ```
  ///
  /// - `d` — exactly one tag, `<chainId>:<role>`: decimal `chainId` (no
  ///   leading zeros, ≤20 digits) `:` one of `summoner` | `factory` |
  ///   `implementation`.
  /// - Tags — exactly one of each: `["chain", "<chainId>"]` (equal to the
  ///   `d` chain segment), `["role", …]` (equal to the `d` role segment),
  ///   `["address", "0x…"]` (40-hex), `["tx", "0x…"]` (32-byte deploying tx
  ///   hash — required, exactly as kind:47005 receipts require theirs, so a
  ///   client can verify the deployment on-chain).
  /// - `content.v` — `1`; `content.block` — non-zero decimal block number the
  ///   contract was deployed in; `content.project` (optional) — launch/org slug
  ///   `[a-z0-9][a-z0-9_-]{0,63}`; `content.note` (optional) — ≤256 chars.
  ///
  /// **Authored by the deployer** (whoever signs with `BUZZ_PRIVATE_KEY`) —
  /// the relay never holds keys. `DeployOrgDao.s.sol` writes the
  /// `deployments/org-dao-<chainid>.json` input (roles + addresses + a
  /// `broadcast` pointer at forge's `run-latest.json`, from which the CLI fills
  /// `tx`/`block` — forge cannot expose the current run's tx hashes inside
  /// `run()`) and prints the exact
  /// `buzz launchpad deployment record --file …` command; the chain is the
  /// ledger, Nostr the record (NIP-LP rule).
  ///
  /// Roles, for a `DeployOrgDao` run: `summoner` = the majeur `Summoner`
  /// CREATE2 factory (`OrgBinding.summoner()`), `factory` = the `OrgBinding`
  /// summon-and-bind entry point, `implementation` = the `Moloch`
  /// implementation the Summoner clones (emitted as `NewDAO` in the
  /// Summoner's constructor).
  static const int KIND_DEPLOYMENT_RECORD = 37018;
}
