import { index, route, rootRoute } from "@tanstack/virtual-file-routes";

export const routes = rootRoute("root.tsx", [
  index("index.tsx"),
  route("/c", "c.tsx"),
  route("/u/$pubkey", "u.$pubkey.tsx"),
  route("/discover", "discover.tsx"),
  route("/c/$host", "c.$host.tsx"),
  route("/identity-demo", "identity-demo.tsx"),
  route("/link-device", "link-device.tsx"),
  route("/invite/$code", "invite.$code.tsx"),
  route("/repos", "repos.tsx"),
  route("/repos/$repoId", "repos.$repoId.tsx"),
  route("/launchpad", "launchpad.tsx"),
  route("/launchpad/$launchId", "launchpad.$launchId.tsx"),
  route("/projects", "projects.tsx"),
  route("/projects/$projectId", "projects.$projectId.tsx"),
  route("/portfolio", "portfolio.tsx"),
  route("/social", "social.tsx"),
  route("/social/explore", "social.explore.tsx"),
  route("/social/notifications", "social.notifications.tsx"),
  route("/social/messages", "social.messages.tsx"),
  route("/social/messages/$peer", "social.messages.$peer.tsx"),
  route("/social/bookmarks", "social.bookmarks.tsx"),
  route("/social/search", "social.search.tsx"),
  route("/social/tag/$tag", "social.tag.$tag.tsx"),
  route("/social/post/$id", "social.post.$id.tsx"),
  route("/repos/$repoId/blob/$", "repos.$repoId.blob.$.tsx"),
]);
