// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as reposRouteImport } from "./routes/repos";
import { Route as feedRouteImport } from "./routes/feed";
import { Route as bookmarksRouteImport } from "./routes/bookmarks";
import { Route as indexRouteImport } from "./routes/index";
import { Route as tagDottagRouteImport } from "./routes/tag.$tag";
import { Route as reposDotrepoIdRouteImport } from "./routes/repos.$repoId";
import { Route as pDotidRouteImport } from "./routes/p.$id";
import { Route as inviteDotcodeRouteImport } from "./routes/invite.$code";
import { Route as feedDotnoteIdRouteImport } from "./routes/feed.$noteId";
import { Route as reposDotrepoIdDotblobDotsplatRouteImport } from "./routes/repos.$repoId.blob.$";

const reposRoute = reposRouteImport.update({
  id: "/repos",
  path: "/repos",
  getParentRoute: () => rootRouteImport,
} as any);
const feedRoute = feedRouteImport.update({
  id: "/feed",
  path: "/feed",
  getParentRoute: () => rootRouteImport,
} as any);
const bookmarksRoute = bookmarksRouteImport.update({
  id: "/bookmarks",
  path: "/bookmarks",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const tagDottagRoute = tagDottagRouteImport.update({
  id: "/tag/$tag",
  path: "/tag/$tag",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdRoute = reposDotrepoIdRouteImport.update({
  id: "/repos/$repoId",
  path: "/repos/$repoId",
  getParentRoute: () => rootRouteImport,
} as any);
const pDotidRoute = pDotidRouteImport.update({
  id: "/p/$id",
  path: "/p/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const inviteDotcodeRoute = inviteDotcodeRouteImport.update({
  id: "/invite/$code",
  path: "/invite/$code",
  getParentRoute: () => rootRouteImport,
} as any);
const feedDotnoteIdRoute = feedDotnoteIdRouteImport.update({
  id: "/feed/$noteId",
  path: "/feed/$noteId",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdDotblobDotsplatRoute =
  reposDotrepoIdDotblobDotsplatRouteImport.update({
    id: "/repos/$repoId/blob/$",
    path: "/repos/$repoId/blob/$",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/bookmarks": typeof bookmarksRoute;
  "/feed": typeof feedRoute;
  "/repos": typeof reposRoute;
  "/feed/$noteId": typeof feedDotnoteIdRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/p/$id": typeof pDotidRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/tag/$tag": typeof tagDottagRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/bookmarks": typeof bookmarksRoute;
  "/feed": typeof feedRoute;
  "/repos": typeof reposRoute;
  "/feed/$noteId": typeof feedDotnoteIdRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/p/$id": typeof pDotidRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/tag/$tag": typeof tagDottagRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/bookmarks": typeof bookmarksRoute;
  "/feed": typeof feedRoute;
  "/repos": typeof reposRoute;
  "/feed/$noteId": typeof feedDotnoteIdRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/p/$id": typeof pDotidRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/tag/$tag": typeof tagDottagRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/bookmarks"
    | "/feed"
    | "/repos"
    | "/feed/$noteId"
    | "/invite/$code"
    | "/p/$id"
    | "/repos/$repoId"
    | "/tag/$tag"
    | "/repos/$repoId/blob/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/bookmarks"
    | "/feed"
    | "/repos"
    | "/feed/$noteId"
    | "/invite/$code"
    | "/p/$id"
    | "/repos/$repoId"
    | "/tag/$tag"
    | "/repos/$repoId/blob/$";
  id:
    | "__root__"
    | "/"
    | "/bookmarks"
    | "/feed"
    | "/repos"
    | "/feed/$noteId"
    | "/invite/$code"
    | "/p/$id"
    | "/repos/$repoId"
    | "/tag/$tag"
    | "/repos/$repoId/blob/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  bookmarksRoute: typeof bookmarksRoute;
  feedRoute: typeof feedRoute;
  reposRoute: typeof reposRoute;
  feedDotnoteIdRoute: typeof feedDotnoteIdRoute;
  inviteDotcodeRoute: typeof inviteDotcodeRoute;
  pDotidRoute: typeof pDotidRoute;
  reposDotrepoIdRoute: typeof reposDotrepoIdRoute;
  tagDottagRoute: typeof tagDottagRoute;
  reposDotrepoIdDotblobDotsplatRoute: typeof reposDotrepoIdDotblobDotsplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/repos": {
      id: "/repos";
      path: "/repos";
      fullPath: "/repos";
      preLoaderRoute: typeof reposRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/feed": {
      id: "/feed";
      path: "/feed";
      fullPath: "/feed";
      preLoaderRoute: typeof feedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/bookmarks": {
      id: "/bookmarks";
      path: "/bookmarks";
      fullPath: "/bookmarks";
      preLoaderRoute: typeof bookmarksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tag/$tag": {
      id: "/tag/$tag";
      path: "/tag/$tag";
      fullPath: "/tag/$tag";
      preLoaderRoute: typeof tagDottagRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId": {
      id: "/repos/$repoId";
      path: "/repos/$repoId";
      fullPath: "/repos/$repoId";
      preLoaderRoute: typeof reposDotrepoIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/p/$id": {
      id: "/p/$id";
      path: "/p/$id";
      fullPath: "/p/$id";
      preLoaderRoute: typeof pDotidRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/invite/$code": {
      id: "/invite/$code";
      path: "/invite/$code";
      fullPath: "/invite/$code";
      preLoaderRoute: typeof inviteDotcodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/feed/$noteId": {
      id: "/feed/$noteId";
      path: "/feed/$noteId";
      fullPath: "/feed/$noteId";
      preLoaderRoute: typeof feedDotnoteIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId/blob/$": {
      id: "/repos/$repoId/blob/$";
      path: "/repos/$repoId/blob/$";
      fullPath: "/repos/$repoId/blob/$";
      preLoaderRoute: typeof reposDotrepoIdDotblobDotsplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  bookmarksRoute: bookmarksRoute,
  feedRoute: feedRoute,
  reposRoute: reposRoute,
  feedDotnoteIdRoute: feedDotnoteIdRoute,
  inviteDotcodeRoute: inviteDotcodeRoute,
  pDotidRoute: pDotidRoute,
  reposDotrepoIdRoute: reposDotrepoIdRoute,
  tagDottagRoute: tagDottagRoute,
  reposDotrepoIdDotblobDotsplatRoute: reposDotrepoIdDotblobDotsplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
