#!/usr/bin/env node
// Regenerates the shared event-kind tables from the Rust registry — the one
// source of truth for every kind integer:
//
//   node scripts/regen-kinds.mjs           # rewrite the generated files
//   node scripts/regen-kinds.mjs --check   # fail when the generated files are stale
//
// Outputs (both @generated; never edit by hand):
//   packages/creaton-core/src/kinds.generated.ts   — shared TS table
//     (web + desktop re-export it via their `shared/constants/kinds.ts`
//     shims and `@creaton/core/kinds.ts`)
//   mobile/lib/shared/kinds.g.dart                 — Dart `Kinds` table
//
// What it parses: `crates/buzz-core/src/kind.rs`, every
// `pub const KIND_*: u32 = <integer>;` plus its contiguous leading comment
// block (`///` docs and `//` notes) verbatim. Client-only aliases and grouped
// kind sets are not registry kinds; they stay hand-written in
// `packages/creaton-core/src/kinds.ts` on top of the generated re-export.
//
// `--check` is the drift gate (wired into web/desktop `pnpm check`): editing
// kind.rs without regenerating, or hand-editing a generated file, fails it.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const KIND_RUST = resolve(repoRoot, "crates/buzz-core/src/kind.rs");
const OUTPUTS = [
  resolve(repoRoot, "packages/creaton-core/src/kinds.generated.ts"),
  resolve(repoRoot, "mobile/lib/shared/kinds.g.dart"),
];

const CONST_RE = /^pub const (KIND_[A-Z0-9_]+): u32 = (\d+);$/;

/**
 * Extract every registry kind with its contiguous leading comment block.
 *
 * @param {string} rust source of crates/buzz-core/src/kind.rs
 * @returns {{ name: string, value: number, comments: string[] }[]} source order
 */
export function parseKindRegistry(rust) {
  const kinds = [];
  let pending = [];
  for (const line of rust.split("\n")) {
    const match = line.match(CONST_RE);
    if (match) {
      kinds.push({ name: match[1], value: Number(match[2]), comments: pending });
      pending = [];
    } else if (/^\s*(\/\/|\/\*)/.test(line)) {
      pending.push(line.trimEnd());
    } else {
      pending = [];
    }
  }
  return kinds;
}

/** @param {{ name: string, value: number, comments: string[] }[]} kinds */
function renderTs(kinds) {
  const body = kinds
    .map(
      (k) =>
        `${[...k.comments, `export const ${k.name} = ${k.value};`].join("\n")}\n`,
    )
    .join("\n");
  return `// @generated by \`just regen-kinds\` (scripts/regen-kinds.mjs) — DO NOT EDIT.
// Source of truth: crates/buzz-core/src/kind.rs. Values and names are wire
// format: change the Rust registry, then run \`just regen-kinds\`.
//
// Client-only aliases and grouped kind sets live in ./kinds.ts on top of this
// table.

${body}`;
}

/** @param {{ name: string, value: number, comments: string[] }[]} kinds */
function renderDart(kinds) {
  const body = kinds
    .map((k) => {
      const comments = k.comments.map((line) => `  ${line.trimEnd()}`);
      return [...comments, `  static const int ${k.name} = ${k.value};`].join(
        "\n",
      );
    })
    .join("\n\n");
  return `// @generated by \`just regen-kinds\` (scripts/regen-kinds.mjs) — DO NOT EDIT.
// Source of truth: crates/buzz-core/src/kind.rs. Values and names are wire
// format: change the Rust registry, then run \`just regen-kinds\`.
// ignore_for_file: constant_identifier_names, doc_markdown, comment_references

/// Event-kind registry mirrored from the relay's Rust source of truth
/// (crates/buzz-core/src/kind.rs).
class Kinds {
  Kinds._();

${body}
}
`;
}

function renderAll() {
  const kinds = parseKindRegistry(readFileSync(KIND_RUST, "utf8"));
  if (kinds.length === 0) {
    throw new Error(`no KIND_ constants parsed from ${KIND_RUST}`);
  }
  return [
    [OUTPUTS[0], renderTs(kinds)],
    [OUTPUTS[1], renderDart(kinds)],
  ];
}

function main() {
  const check = process.argv.includes("--check");
  const stale = [];
  for (const [path, content] of renderAll()) {
    let disk = null;
    try {
      disk = readFileSync(path, "utf8");
    } catch {
      // Missing file counts as stale below.
    }
    if (check) {
      if (disk !== content) stale.push(path);
    } else {
      if (disk !== content) {
        writeFileSync(path, content);
        console.log(`regen-kinds: wrote ${path}`);
      }
    }
  }
  if (check) {
    if (stale.length > 0) {
      console.error("regen-kinds: generated kind tables are STALE:");
      for (const path of stale) console.error(`  ${path}`);
      console.error("Run `just regen-kinds` and commit the result.");
      process.exit(1);
    }
    console.log("regen-kinds: generated kind tables are up to date");
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
