// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `conversation_key_from_slice`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`, `from`, `source`

/// Derive a NIP-44 v2 conversation key from a sender secret key and the
/// receiver public key (both hex-encoded).
///
/// Returns the raw 32-byte conversation key. The derivation is symmetric:
/// `(secret_a, public_b)` and `(secret_b, public_a)` yield the same key, so
/// callers can cache one key per peer pair.
Uint8List getConversationKey({
  required String senderSecretHex,
  required String receiverPublicHex,
}) => RustLib.instance.api.crateApiGetConversationKey(
  senderSecretHex: senderSecretHex,
  receiverPublicHex: receiverPublicHex,
);

/// Encrypt `plaintext` with NIP-44 v2 under `conversation_key`.
///
/// `plaintext` must be 1-65535 UTF-8 bytes. Returns the standard base64
/// payload: `version(1) || nonce(32) || ciphertext || mac(32)`.
String nip44Encrypt({
  required List<int> conversationKey,
  required String plaintext,
}) => RustLib.instance.api.crateApiNip44Encrypt(
  conversationKey: conversationKey,
  plaintext: plaintext,
);

/// Decrypt a standard base64 NIP-44 v2 `payload_base64` under
/// `conversation_key`.
///
/// The payload is size-bounded and version-checked before decoding per the
/// NIP-44 guidance, then authenticated (HMAC) before decrypting. Returns the
/// UTF-8 plaintext.
String nip44Decrypt({
  required List<int> conversationKey,
  required String payloadBase64,
}) => RustLib.instance.api.crateApiNip44Decrypt(
  conversationKey: conversationKey,
  payloadBase64: payloadBase64,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ClientCoreError>>
abstract class ClientCoreError implements RustOpaqueInterface {}
